name: Gecko CI

on: [push, pull_request]

jobs:
  Windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set tag to git commit
        run: git config user.name "Buildbot" && git config -user.email "gecko@build.bot" && git tag -a ${GITHUB_SHA} -m "Tagging commit" && git push origin ${GITHUB_SHA}

      - name: Dpkg 32-bit
        run: sudo dpkg --add-architecture i386 && sudo apt update

      - name: Setup Wine & Python
        run: sudo apt install wine wine32 python3
        
      - name: Compile C Code to ASM
        run: python3 c_to_codewrite.py src/shops.c src/include/mp5.us.lst
        
      - name: Compile ASM Code to PowerPC Binary
        run: wine compiler/codewrite/powerpc-gekko-as.exe -a32 -mbig -mregnames -mgekko src/shops.s 

      - name: Compile PowerPC Binary to Gecko Code
        run: python3 gecko.py a.out 800C0950 code.txt

      - name: Upload Gecko Code
        uses: actions/upload-artifact@v4
        with:
          name: MP5ShopMod-Gecko
          path: code.txt

      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.3
        env:
            GHR_COMPRESS: zip
            GHR_PATH: code.txt
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
