name: Gecko CI

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-2022
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.10

      - name: Compile C Code to ASM
        run: python3 c_to_codewrite.py src/shops.c src/include/mp5.us.lst
        
      - name: Compile ASM Code to PowerPC Binary
        run: compiler/codewrite/powerpc-gekko-as.exe -a32 -mbig -mregnames -mgekko src/shops.s 

      - name: Compile PowerPC Binary to Gecko Code
        run: python3 gecko.py a.out 800C0950 code.txt

      - name: Upload Gecko Code
        uses: actions/upload-artifact@v4
        with:
          name: MP5ShopMod-Gecko
          path: code.txt
